---
- hosts: all
  user: "{{deploy_user}}"
  vars_files:
    - vars.yml
  tasks:
  - name: Backup Database
    mysql_db: name={{db_name}} login_user={{mysql_user}} login_password={{mysql_password}} state=dump target=/tmp/{{db_name}}-{{ansible_date_time.date}}.sql
